"""Rebuild the static demo pages from data/resources.json (Python 3; no packages)."""
import json, pathlib, html
SITE=pathlib.Path(__file__).resolve().parents[1]
BASE='/factors-faq-agent-demo/'
HOST='https://jesse-docket.github.io'
E=html.escape
catalog=json.loads((SITE/'data/resources.json').read_text())
tools=[r for r in catalog if r['type']=='tool']
reports=[r for r in catalog if r['type']=='report']
byid={r['id']:r for r in catalog}
def a(path,text,cls=''):return f'<a class="{cls}" href="{E(path)}">{text}</a>'
def cards(rows):return '<div class="cards">'+''.join(f'<article class="card" data-resource="{r["id"]}" data-topic="{E(r["topic"])}" data-search="{E((r["title"]+" "+r["topic"]+" "+r["intent"]+" "+r["speaker"]).lower())}"><div class="tag">{E(r["topic"])} / {E(r["status"])}</div><h3>{a(r["path"],E(r["title"]))}</h3><p>{E(r["summary"])}</p><div class="card-bottom">{a(r["path"],"Explore resource →","text-link")}</div></article>' for r in rows)+'</div>'
def faq(rows):return '<section class="faq" id="faq"><h2>Frequently asked questions</h2>'+''.join(f'<details class="qrow"><summary><span class="qtext">{E(q)}</span></summary><div class="ans"><p>{ans}</p></div></details>' for q,ans in rows)+'</section>'
def shell(title,content):
 return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>{E(title)} | Factors resource demo</title><link rel="stylesheet" href="{BASE}assets/site.css"><script defer src="{BASE}assets/site.js"></script></head><body><a class="skip" href="#main">Skip to content</a><div class="announce">Explore the ideas behind better B2B marketing. {a(BASE+'tools/','Discover the free tools →')}</div><nav aria-label="Main navigation"><div class="nav-inner">{a(BASE,'factors<span class="brand-dot">.</span>ai','brand')}<div class="nav-links">{a(BASE+'tools/','Free Tools')}{a(BASE+'webinars/','Webinars')}{a(BASE+'reports/','Report')}{a(BASE+'#faq','Questions')}</div></div></nav><main id="main" class="wrap">{content}</main><footer><div class="wrap"><strong>Factors resource demo</strong><p>Demonstration website for reviewing Factors Guide. Sample outputs are illustrative. Original resource content belongs to Factors and the credited speakers.</p>{a(BASE,'Home')} · {a(BASE+'tools/','Free Tools')} · {a(BASE+'webinars/','Webinars')} · {a(BASE+'reports/','Report')}</div></footer><script src="{BASE}assets/widget.js"></script></body></html>'''
def write(path,title,body):
 target=SITE/path.removeprefix(BASE)/'index.html';target.parent.mkdir(parents=True,exist_ok=True);target.write_text(shell(title,body))
common=[('Can I explore without sharing my email?','Yes. These resource summaries and sample previews are available without an email gate.'),('Can Factors Guide show me where to look?','Ask the agent about your objective or a specific topic. When a relevant resource matches, it can guide you to the page and explain the useful sections.'),('Does this site generate reports or play webinars?','No. This demonstration contains written session summaries and illustrative tool previews. It does not submit forms, send reports or play recordings.')]
home='''<header class="hero"><div class="eyebrow">AI-powered account-based marketing</div><h1>Your next marketing move.<br><span>Start with a useful idea.</span></h1><p class="lede">Explore practical playbooks, free tools and conversations with B2B marketers. Factors Guide can help you find the resource that fits your goal—and show you where to start.</p><div class="actions">'''+a(BASE+'webinars/','Explore webinars','button primary')+a(BASE+'tools/','Discover free tools','button')+'''</div></header><section><div class="section-head"><div class="eyebrow">From questions to next steps</div><h2>What are you working on?</h2></div><div class="paths">'''+''.join(a(p,f'<span>{n}</span><small>{s}</small>','path-card') for p,n,s in [(tools[0]['path'],'Find in-market accounts','Explore category-level buyer intent'),(tools[1]['path'],'Improve LinkedIn creative','Compare messaging and positioning'),(BASE+'webinars/?topic=ABM%20strategy','Build your ABM strategy','Find a framework for your next campaign')])+'''</div></section><section><div class="section-head"><div class="eyebrow">Practical starting points</div><h2>Tools to make the next step clearer.</h2></div>'''+cards(tools)+'''</section><section><div class="section-head"><div class="eyebrow">Learn from practitioners</div><h2>Ideas worth bringing to your team.</h2></div>'''+cards([byid['W04'],byid['W06'],byid['W02']])+a(BASE+'webinars/','Browse all 11 sessions →','text-link')+'</section>'+'''<section><div class="section-head"><div class="eyebrow">New benchmark research</div><h2>The data behind the decisions.</h2></div>'''+cards(reports)+'</section>'+faq([('What does Factors help marketers do?','Factors brings together account engagement, intent and attribution to help teams understand which accounts to prioritize and how marketing contributes to pipeline.'),('Which resource should I start with?',f'For account discovery, explore {a(tools[0]["path"],"Buyer Intent Data")}. For competitive creative research, try {a(tools[1]["path"],"LinkedIn Advisor")}. For methods and examples, browse the webinar library.')]+common)
write(BASE,'Explore ABM, intent and LinkedIn ads',home)
webinars=[r for r in catalog if r['type']=='webinar'];topics=sorted(set(r['topic'] for r in webinars))
filters='<div class="filters"><label>Search sessions<input id="search" type="search" placeholder="Try ABM, CAPI, AI or a speaker"></label><label>Topic<select id="topic"><option value="">All topics</option>'+''.join(f'<option>{E(t)}</option>' for t in topics)+'</select></label></div><p id="result-count" role="status">11 sessions</p>'
write(BASE+'webinars/','Webinars','<header class="hero compact"><div class="eyebrow">The resource library</div><h1>Find the conversation<br>for your next challenge.</h1><p class="lede">Practical lessons in ABM, paid media, operations and buyer engagement. Explore written summaries, then take the relevant ideas back to your team.</p></header>'+filters+cards(webinars)+'<p id="empty" hidden>No sessions match. Try another topic or clear the search.</p>'+faq([('How do I find the right session?','Filter by topic or search for your challenge, a title or a speaker. Ask Factors Guide if you want help choosing between similar sessions.'),('Are all sessions new recordings from 2026?','No. This library includes past 2026 events and archival conversations with 2026 page dates. Each page explains the date evidence.')]+common))
write(BASE+'tools/','Free Tools','<header class="hero compact"><div class="eyebrow">Free tools</div><h1>A practical starting point<br>for your next campaign.</h1><p class="lede">Explore what buyer-intent research and competitive ad analysis can add to your planning. These pages show sample outputs for demonstration.</p></header>'+cards(tools)+faq([('Which tool fits my objective?','Use Buyer Intent Data for category-level account discovery. Use LinkedIn Advisor for competitor messaging and creative research.')]+common))
write(BASE+'reports/','Report','<header class="hero compact"><div class="eyebrow">Benchmark research</div><h1>The data behind<br>the decisions.</h1><p class="lede">Published benchmark research for B2B marketing and revenue teams. Explore what the numbers say, then take the relevant ideas back to your team.</p></header>'+cards(reports)+faq([('What is in this report?','Benchmark research across 50,000 closed deals, 850+ B2B companies and $150M+ in LinkedIn ad spend, covering channel mix, revenue quality, buying-committee coverage and the buyer research window.'),('Is this the real report?','No. This is a demonstration replica of the published Factors landing page. The form does not submit and the report is not delivered here.')]+common))
for r in catalog:
 date=f'Event: {r["event_date"]}' if r['event_date'] else 'Original event date unverified'
 if r['page_date']:date+=' · Source page date: '+r['page_date']
 if r['type']=='tool':date='Illustrative preview · No submission required'
 if r['type']=='report':date='Demonstration replica · Source page date: '+r['page_date']
 body=f'<div class="breadcrumbs">{a(BASE,"Home")} / {a(BASE+{"webinar":"webinars/","tool":"tools/"}.get(r["type"],"reports/"),{"webinar":"Webinars","tool":"Free Tools"}.get(r["type"],"Report"))}</div><header class="hero compact"><div class="eyebrow">{E(r["topic"])} / {E(r["status"])}</div><h1>{E(r["title"])}</h1><p class="speaker">{E(r["speaker"])}</p><p class="meta">{E(date)}</p></header><div class="article-grid"><article><section id="overview"><h2>Overview</h2><p class="intro">{E(r["summary"])}</p></section><section id="takeaways"><h2>Key takeaways</h2><ol class="takeaways">'+''.join(f'<li>{E(t)}</li>' for t in r['takeaways'])+f'</ol></section><section id="when-this-helps"><h2>When this helps</h2><p>{E(r["intent"])}</p><p><strong>Try asking:</strong> “{E(r["example"])}”</p></section>'
 if r['type']=='tool':
  if r['id']=='LM01':sample='<table><caption>Fictional account examples</caption><thead><tr><th>Account</th><th>Research category</th><th>Planning question</th></tr></thead><tbody><tr><td>Example Company A</td><td>Marketing attribution</td><td>Does this account fit our ICP?</td></tr><tr><td>Example Company B</td><td>Account-based marketing</td><td>Which additional signals support outreach?</td></tr><tr><td>Example Company C</td><td>Revenue analytics</td><td>What problem could relevant content address?</td></tr></tbody></table>'
  else:sample='<table><caption>Fictional competitor comparison</caption><thead><tr><th>Example</th><th>Messaging emphasis</th><th>Creative hypothesis</th></tr></thead><tbody><tr><td>Competitor A</td><td>Save reporting time</td><td>Show a concrete workflow</td></tr><tr><td>Competitor B</td><td>Prove marketing impact</td><td>Explain the measurement approach</td></tr><tr><td>Competitor C</td><td>Align account activity</td><td>Test a buying-committee story</td></tr></tbody></table>'
  body+='<section id="sample-preview"><h2>Sample preview</h2><p class="notice">Illustrative examples only. No live account research or competitor analysis has been performed.</p><details class="preview"><summary>Show sample preview</summary><div class="table-scroll">'+sample+'</div></details></section>'

 if r['type']=='report':
  body+='<section id="get-the-report"><h2>Get the report</h2><form class="lp-form" id="lp-form" novalidate><label for="fn">First Name</label><input id="fn" name="firstname" type="text" placeholder="First Name" autocomplete="off"><label for="em">Business Email</label><input id="em" name="email" type="email" placeholder="Business Email" autocomplete="off"><fieldset><legend>Are you interested in a free LinkedIn ads consultation?</legend><div class="radios"><label><input type="radio" name="consult" value="yes"> Yes</label><label><input type="radio" name="consult" value="no"> No</label></div></fieldset><button type="submit">Download the report</button><p class="notice">Demonstration page. Nothing is submitted or stored, no report is delivered and no consultation is arranged.</p></form><div id="lp-done" role="status" hidden><strong>That&rsquo;s the capture moment.</strong><p class="notice">On the live page this is where the name, business email and consultation preference would be written back. Nothing was sent here.</p></div><style>.lp-form{max-width:520px}.lp-form label{display:block;font-weight:600;margin:14px 0 6px}.lp-form input[type=text],.lp-form input[type=email]{width:100%;padding:11px 13px;border:1px solid #d5d5dd;border-radius:6px;font:inherit;background:#fff}.lp-form fieldset{border:0;padding:0;margin:18px 0 0}.lp-form legend{font-weight:600;margin-bottom:8px}.lp-form .radios label{display:inline-flex;align-items:center;gap:6px;font-weight:400;margin:0 18px 0 0}.lp-form button{margin-top:20px;padding:12px 22px;border:0;border-radius:6px;background:#E8383D;color:#fff;font:inherit;font-weight:600;cursor:pointer}.lp-form button:hover{background:#c92d32}#lp-done{padding:18px;border:1px solid #cfe6d4;background:#f2faf4;border-radius:8px}</style><script>document.getElementById("lp-form").addEventListener("submit",function(e){e.preventDefault();this.hidden=true;var d=document.getElementById("lp-done");d.hidden=false;d.scrollIntoView({behavior:"smooth",block:"center"});});</script></section>'
 body+=f'</article><aside><div class="aside-card"><div class="eyebrow">Who this is for</div><p>{E(r["audience"])}</p><hr><strong>On this page</strong><ul><li>{a("#overview","Overview")}</li><li>{a("#takeaways","Key takeaways")}</li><li>{a("#when-this-helps","When this helps")}</li></ul><p class="meta">{E(r["date_note"])}</p>{a(r["source"],"View original Factors page ↗","source-link")}</div></aside></div><section><div class="section-head"><h2>Keep exploring</h2></div>'+cards([byid[i] for i in r['related']])+'</section>'
 body+=faq([('What will I learn here?',E(r['summary'])),('Who is this resource for?',E(r['audience'])+'.'),('When is a different resource a better fit?',E(r['exclude'])),common[0],common[2]])
 write(r['path'],r['title'],body)
print(f'Built {len(catalog)+4} pages from the shared catalog')
